"""empty message

Revision ID: 3fc485f5630a
Revises: 4b80190d4a75
Create Date: 2015-03-31 15:28:53.265872

"""

# revision identifiers, used by Alembic.
revision = '3fc485f5630a'
down_revision = '4b80190d4a75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
