"""empty message

Revision ID: 4b80190d4a75
Revises: 4ef17208f9fb
Create Date: 2015-03-31 15:09:57.179421

"""

# revision identifiers, used by Alembic.
revision = '4b80190d4a75'
down_revision = '4ef17208f9fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_id', sa.String(length=64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_id')
    ### end Alembic commands ###
