"""empty message

Revision ID: 4ef17208f9fb
Revises: 35b03e7946a0
Create Date: 2015-03-23 17:48:55.170239

"""

# revision identifiers, used by Alembic.
revision = '4ef17208f9fb'
down_revision = '35b03e7946a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('end_first_round', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('end_second_round', sa.Date(), nullable=True))
    op.create_index('ix_projects_end_first_round', 'projects', ['end_first_round'], unique=False)
    op.create_index('ix_projects_end_second_round', 'projects', ['end_second_round'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_end_second_round', 'projects')
    op.drop_index('ix_projects_end_first_round', 'projects')
    op.drop_column('projects', 'end_second_round')
    op.drop_column('projects', 'end_first_round')
    ### end Alembic commands ###
