"""empty message

Revision ID: 5239db16c08
Revises: 3fc485f5630a
Create Date: 2015-03-31 15:47:31.683907

"""

# revision identifiers, used by Alembic.
revision = '5239db16c08'
down_revision = '3fc485f5630a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_id', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_id')
    ### end Alembic commands ###
